// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/osa-overrides/overrides.proto

package go_micro_srv_overrides

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OSASha struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sha                  string   `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OSASha) Reset()         { *m = OSASha{} }
func (m *OSASha) String() string { return proto.CompactTextString(m) }
func (*OSASha) ProtoMessage()    {}
func (*OSASha) Descriptor() ([]byte, []int) {
	return fileDescriptor_43700de1fd2159ba, []int{0}
}

func (m *OSASha) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OSASha.Unmarshal(m, b)
}
func (m *OSASha) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OSASha.Marshal(b, m, deterministic)
}
func (m *OSASha) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OSASha.Merge(m, src)
}
func (m *OSASha) XXX_Size() int {
	return xxx_messageInfo_OSASha.Size(m)
}
func (m *OSASha) XXX_DiscardUnknown() {
	xxx_messageInfo_OSASha.DiscardUnknown(m)
}

var xxx_messageInfo_OSASha proto.InternalMessageInfo

func (m *OSASha) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OSASha) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type DefaultsFile struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Contents             string   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultsFile) Reset()         { *m = DefaultsFile{} }
func (m *DefaultsFile) String() string { return proto.CompactTextString(m) }
func (*DefaultsFile) ProtoMessage()    {}
func (*DefaultsFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_43700de1fd2159ba, []int{1}
}

func (m *DefaultsFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultsFile.Unmarshal(m, b)
}
func (m *DefaultsFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultsFile.Marshal(b, m, deterministic)
}
func (m *DefaultsFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultsFile.Merge(m, src)
}
func (m *DefaultsFile) XXX_Size() int {
	return xxx_messageInfo_DefaultsFile.Size(m)
}
func (m *DefaultsFile) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultsFile.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultsFile proto.InternalMessageInfo

func (m *DefaultsFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DefaultsFile) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

type OSADefaults struct {
	Valid                bool            `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Defailts             []*DefaultsFile `protobuf:"bytes,2,rep,name=defailts,proto3" json:"defailts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OSADefaults) Reset()         { *m = OSADefaults{} }
func (m *OSADefaults) String() string { return proto.CompactTextString(m) }
func (*OSADefaults) ProtoMessage()    {}
func (*OSADefaults) Descriptor() ([]byte, []int) {
	return fileDescriptor_43700de1fd2159ba, []int{2}
}

func (m *OSADefaults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OSADefaults.Unmarshal(m, b)
}
func (m *OSADefaults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OSADefaults.Marshal(b, m, deterministic)
}
func (m *OSADefaults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OSADefaults.Merge(m, src)
}
func (m *OSADefaults) XXX_Size() int {
	return xxx_messageInfo_OSADefaults.Size(m)
}
func (m *OSADefaults) XXX_DiscardUnknown() {
	xxx_messageInfo_OSADefaults.DiscardUnknown(m)
}

var xxx_messageInfo_OSADefaults proto.InternalMessageInfo

func (m *OSADefaults) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *OSADefaults) GetDefailts() []*DefaultsFile {
	if m != nil {
		return m.Defailts
	}
	return nil
}

func init() {
	proto.RegisterType((*OSASha)(nil), "go.micro.srv.overrides.OSASha")
	proto.RegisterType((*DefaultsFile)(nil), "go.micro.srv.overrides.DefaultsFile")
	proto.RegisterType((*OSADefaults)(nil), "go.micro.srv.overrides.OSADefaults")
}

func init() {
	proto.RegisterFile("proto/osa-overrides/overrides.proto", fileDescriptor_43700de1fd2159ba)
}

var fileDescriptor_43700de1fd2159ba = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x6d, 0xaa, 0x25, 0x4e, 0xa5, 0xe8, 0x20, 0x52, 0x7a, 0x10, 0x49, 0x3d, 0x14, 0xc1,
	0x2d, 0xd4, 0xbb, 0x58, 0x10, 0x7b, 0x0c, 0x24, 0x07, 0xcf, 0x63, 0x33, 0x35, 0x0b, 0x6b, 0xa6,
	0xec, 0xae, 0xf9, 0xfd, 0xe2, 0x36, 0x5d, 0x7a, 0xd0, 0xde, 0xde, 0xec, 0xdb, 0xf7, 0xcd, 0xf0,
	0x60, 0xba, 0xb5, 0xe2, 0x65, 0x2e, 0x8e, 0x1e, 0xa5, 0x65, 0x6b, 0x75, 0xc5, 0x6e, 0x1e, 0x95,
	0x0a, 0x2e, 0xde, 0x7c, 0x8a, 0xfa, 0xd2, 0x6b, 0x2b, 0xca, 0xd9, 0x56, 0x45, 0x37, 0x7b, 0x80,
	0x41, 0x5e, 0x2e, 0xcb, 0x9a, 0x70, 0x04, 0x89, 0xae, 0xc6, 0xbd, 0xbb, 0xde, 0xec, 0xbc, 0x48,
	0x74, 0x85, 0x97, 0xd0, 0x77, 0x35, 0x8d, 0x93, 0xf0, 0xf0, 0x2b, 0xb3, 0x67, 0xb8, 0x78, 0xe5,
	0x0d, 0x7d, 0x1b, 0xef, 0xde, 0xb4, 0x61, 0x44, 0x38, 0xdd, 0x92, 0xaf, 0xbb, 0x4c, 0xd0, 0x38,
	0x81, 0x74, 0x2d, 0x8d, 0xe7, 0xc6, 0xbb, 0x2e, 0x1a, 0xe7, 0x8c, 0x61, 0x98, 0x97, 0xcb, 0x3d,
	0x02, 0xaf, 0xe1, 0xac, 0x25, 0xd3, 0xed, 0x4c, 0x8b, 0xdd, 0x80, 0x2f, 0x90, 0x56, 0xbc, 0x21,
	0x6d, 0x02, 0xa0, 0x3f, 0x1b, 0x2e, 0xee, 0xd5, 0xdf, 0xb7, 0xab, 0xc3, 0x63, 0x8a, 0x98, 0x5a,
	0x18, 0xb8, 0xca, 0xbb, 0x3f, 0x2b, 0x6e, 0xd8, 0x92, 0x17, 0x8b, 0xef, 0x30, 0x5a, 0xb1, 0x3f,
	0x5c, 0x7f, 0xfb, 0x1f, 0x76, 0xd7, 0xc7, 0x64, 0x7a, 0xc4, 0xdf, 0x43, 0xb2, 0x93, 0x8f, 0x41,
	0xe8, 0xf7, 0xe9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xf1, 0xe4, 0x7b, 0x86, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OverrideGeneratorClient is the client API for OverrideGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OverrideGeneratorClient interface {
	GetOSADefaults(ctx context.Context, in *OSASha, opts ...grpc.CallOption) (*OSADefaults, error)
}

type overrideGeneratorClient struct {
	cc *grpc.ClientConn
}

func NewOverrideGeneratorClient(cc *grpc.ClientConn) OverrideGeneratorClient {
	return &overrideGeneratorClient{cc}
}

func (c *overrideGeneratorClient) GetOSADefaults(ctx context.Context, in *OSASha, opts ...grpc.CallOption) (*OSADefaults, error) {
	out := new(OSADefaults)
	err := c.cc.Invoke(ctx, "/go.micro.srv.overrides.OverrideGenerator/GetOSADefaults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OverrideGeneratorServer is the server API for OverrideGenerator service.
type OverrideGeneratorServer interface {
	GetOSADefaults(context.Context, *OSASha) (*OSADefaults, error)
}

func RegisterOverrideGeneratorServer(s *grpc.Server, srv OverrideGeneratorServer) {
	s.RegisterService(&_OverrideGenerator_serviceDesc, srv)
}

func _OverrideGenerator_GetOSADefaults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OSASha)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverrideGeneratorServer).GetOSADefaults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.overrides.OverrideGenerator/GetOSADefaults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverrideGeneratorServer).GetOSADefaults(ctx, req.(*OSASha))
	}
	return interceptor(ctx, in, info, handler)
}

var _OverrideGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.overrides.OverrideGenerator",
	HandlerType: (*OverrideGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOSADefaults",
			Handler:    _OverrideGenerator_GetOSADefaults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/osa-overrides/overrides.proto",
}
